
### Test of API request using all in place of ID
GET https://api.tfl.gov.uk/Road/all/Disruption?app_id=API_engage_squared&app_key=9fa83c22a4a34be3b8b82b3f35de0828
content-type: application/json
cors: include